#server
server:
  port: 8081
#logging
logging:
  config: classpath:logback.xml

#jasypt
jasypt:
  encryptor:
    password: 7T0sU6q%XY$Al39LP4BJUgwd$hGy*Fk81

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.93:3306/emr-cdss-extract?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: DatebookHikariCP
