package com.yx.cdss.extract.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table drug_medica_lorders_detail
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class DrugMedicaLordersDetail implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.dmld
     *
     * @mbg.generated
     */
    private Long dmld;

    /**
     * Database Column Remarks:
     *   医嘱ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.medical_orders_id
     *
     * @mbg.generated
     */
    private String medicalOrdersId;

    /**
     * Database Column Remarks:
     *   患�?�ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     * Database Column Remarks:
     *   住院�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.admission_number
     *
     * @mbg.generated
     */
    private String admissionNumber;

    /**
     * Database Column Remarks:
     *   组编�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.group_code
     *
     * @mbg.generated
     */
    private String groupCode;

    /**
     * Database Column Remarks:
     *   药品名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.drug_name
     *
     * @mbg.generated
     */
    private String drugName;

    /**
     * Database Column Remarks:
     *   药品编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.drug_code
     *
     * @mbg.generated
     */
    private String drugCode;

    /**
     * Database Column Remarks:
     *   用药频次
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.frequent_of_medications
     *
     * @mbg.generated
     */
    private Integer frequentOfMedications;

    /**
     * Database Column Remarks:
     *   单次剂量
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.dose_of_einmal
     *
     * @mbg.generated
     */
    private Double doseOfEinmal;

    /**
     * Database Column Remarks:
     *   剂量单位
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.dose_units
     *
     * @mbg.generated
     */
    private String doseUnits;

    /**
     * Database Column Remarks:
     *   给药途径
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.route_of_given_drug
     *
     * @mbg.generated
     */
    private String routeOfGivenDrug;

    /**
     * Database Column Remarks:
     *   药品规格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.drug_specifications
     *
     * @mbg.generated
     */
    private String drugSpecifications;

    /**
     * Database Column Remarks:
     *   是否为抗生素:0-�?,1-�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.isAntibiotic
     *
     * @mbg.generated
     */
    private Short isantibiotic;

    /**
     * Database Column Remarks:
     *   �?属医院编�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * Database Column Remarks:
     *   记录状�??:1-进行�?,2-完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.record_status
     *
     * @mbg.generated
     */
    private Integer recordStatus;

    /**
     * Database Column Remarks:
     *   抽取时间,数据同步�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.extract_time
     *
     * @mbg.generated
     */
    private Date extractTime;

    /**
     * Database Column Remarks:
     *   预留字段1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.attribute1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   预留字段2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.attribute2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   预留字段3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.attribute3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   预留字段4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.attribute4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   预留字段5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column drug_medica_lorders_detail.attribute5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table drug_medica_lorders_detail
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.dmld
     *
     * @return the value of drug_medica_lorders_detail.dmld
     *
     * @mbg.generated
     */
    public Long getDmld() {
        return dmld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.dmld
     *
     * @param dmld the value for drug_medica_lorders_detail.dmld
     *
     * @mbg.generated
     */
    public void setDmld(Long dmld) {
        this.dmld = dmld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.medical_orders_id
     *
     * @return the value of drug_medica_lorders_detail.medical_orders_id
     *
     * @mbg.generated
     */
    public String getMedicalOrdersId() {
        return medicalOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.medical_orders_id
     *
     * @param medicalOrdersId the value for drug_medica_lorders_detail.medical_orders_id
     *
     * @mbg.generated
     */
    public void setMedicalOrdersId(String medicalOrdersId) {
        this.medicalOrdersId = medicalOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.patient_id
     *
     * @return the value of drug_medica_lorders_detail.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.patient_id
     *
     * @param patientId the value for drug_medica_lorders_detail.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.admission_number
     *
     * @return the value of drug_medica_lorders_detail.admission_number
     *
     * @mbg.generated
     */
    public String getAdmissionNumber() {
        return admissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.admission_number
     *
     * @param admissionNumber the value for drug_medica_lorders_detail.admission_number
     *
     * @mbg.generated
     */
    public void setAdmissionNumber(String admissionNumber) {
        this.admissionNumber = admissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.group_code
     *
     * @return the value of drug_medica_lorders_detail.group_code
     *
     * @mbg.generated
     */
    public String getGroupCode() {
        return groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.group_code
     *
     * @param groupCode the value for drug_medica_lorders_detail.group_code
     *
     * @mbg.generated
     */
    public void setGroupCode(String groupCode) {
        this.groupCode = groupCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.drug_name
     *
     * @return the value of drug_medica_lorders_detail.drug_name
     *
     * @mbg.generated
     */
    public String getDrugName() {
        return drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.drug_name
     *
     * @param drugName the value for drug_medica_lorders_detail.drug_name
     *
     * @mbg.generated
     */
    public void setDrugName(String drugName) {
        this.drugName = drugName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.drug_code
     *
     * @return the value of drug_medica_lorders_detail.drug_code
     *
     * @mbg.generated
     */
    public String getDrugCode() {
        return drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.drug_code
     *
     * @param drugCode the value for drug_medica_lorders_detail.drug_code
     *
     * @mbg.generated
     */
    public void setDrugCode(String drugCode) {
        this.drugCode = drugCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.frequent_of_medications
     *
     * @return the value of drug_medica_lorders_detail.frequent_of_medications
     *
     * @mbg.generated
     */
    public Integer getFrequentOfMedications() {
        return frequentOfMedications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.frequent_of_medications
     *
     * @param frequentOfMedications the value for drug_medica_lorders_detail.frequent_of_medications
     *
     * @mbg.generated
     */
    public void setFrequentOfMedications(Integer frequentOfMedications) {
        this.frequentOfMedications = frequentOfMedications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.dose_of_einmal
     *
     * @return the value of drug_medica_lorders_detail.dose_of_einmal
     *
     * @mbg.generated
     */
    public Double getDoseOfEinmal() {
        return doseOfEinmal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.dose_of_einmal
     *
     * @param doseOfEinmal the value for drug_medica_lorders_detail.dose_of_einmal
     *
     * @mbg.generated
     */
    public void setDoseOfEinmal(Double doseOfEinmal) {
        this.doseOfEinmal = doseOfEinmal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.dose_units
     *
     * @return the value of drug_medica_lorders_detail.dose_units
     *
     * @mbg.generated
     */
    public String getDoseUnits() {
        return doseUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.dose_units
     *
     * @param doseUnits the value for drug_medica_lorders_detail.dose_units
     *
     * @mbg.generated
     */
    public void setDoseUnits(String doseUnits) {
        this.doseUnits = doseUnits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.route_of_given_drug
     *
     * @return the value of drug_medica_lorders_detail.route_of_given_drug
     *
     * @mbg.generated
     */
    public String getRouteOfGivenDrug() {
        return routeOfGivenDrug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.route_of_given_drug
     *
     * @param routeOfGivenDrug the value for drug_medica_lorders_detail.route_of_given_drug
     *
     * @mbg.generated
     */
    public void setRouteOfGivenDrug(String routeOfGivenDrug) {
        this.routeOfGivenDrug = routeOfGivenDrug;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.drug_specifications
     *
     * @return the value of drug_medica_lorders_detail.drug_specifications
     *
     * @mbg.generated
     */
    public String getDrugSpecifications() {
        return drugSpecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.drug_specifications
     *
     * @param drugSpecifications the value for drug_medica_lorders_detail.drug_specifications
     *
     * @mbg.generated
     */
    public void setDrugSpecifications(String drugSpecifications) {
        this.drugSpecifications = drugSpecifications;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.isAntibiotic
     *
     * @return the value of drug_medica_lorders_detail.isAntibiotic
     *
     * @mbg.generated
     */
    public Short getIsantibiotic() {
        return isantibiotic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.isAntibiotic
     *
     * @param isantibiotic the value for drug_medica_lorders_detail.isAntibiotic
     *
     * @mbg.generated
     */
    public void setIsantibiotic(Short isantibiotic) {
        this.isantibiotic = isantibiotic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.hospital_code
     *
     * @return the value of drug_medica_lorders_detail.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.hospital_code
     *
     * @param hospitalCode the value for drug_medica_lorders_detail.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.record_status
     *
     * @return the value of drug_medica_lorders_detail.record_status
     *
     * @mbg.generated
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.record_status
     *
     * @param recordStatus the value for drug_medica_lorders_detail.record_status
     *
     * @mbg.generated
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.extract_time
     *
     * @return the value of drug_medica_lorders_detail.extract_time
     *
     * @mbg.generated
     */
    public Date getExtractTime() {
        return extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.extract_time
     *
     * @param extractTime the value for drug_medica_lorders_detail.extract_time
     *
     * @mbg.generated
     */
    public void setExtractTime(Date extractTime) {
        this.extractTime = extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.attribute1
     *
     * @return the value of drug_medica_lorders_detail.attribute1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.attribute1
     *
     * @param attribute1 the value for drug_medica_lorders_detail.attribute1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.attribute2
     *
     * @return the value of drug_medica_lorders_detail.attribute2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.attribute2
     *
     * @param attribute2 the value for drug_medica_lorders_detail.attribute2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.attribute3
     *
     * @return the value of drug_medica_lorders_detail.attribute3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.attribute3
     *
     * @param attribute3 the value for drug_medica_lorders_detail.attribute3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.attribute4
     *
     * @return the value of drug_medica_lorders_detail.attribute4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.attribute4
     *
     * @param attribute4 the value for drug_medica_lorders_detail.attribute4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column drug_medica_lorders_detail.attribute5
     *
     * @return the value of drug_medica_lorders_detail.attribute5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column drug_medica_lorders_detail.attribute5
     *
     * @param attribute5 the value for drug_medica_lorders_detail.attribute5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
}