package com.yx.cdss.extract.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table examine_info_report
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ExamineInfoReport implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.eir_id
     *
     * @mbg.generated
     */
    private Long eirId;

    /**
     * Database Column Remarks:
     *   患�?�ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     * Database Column Remarks:
     *   住院�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.adminission_number
     *
     * @mbg.generated
     */
    private String adminissionNumber;

    /**
     * Database Column Remarks:
     *   �?验申请单�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     * Database Column Remarks:
     *   �?验报告单�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.report_number
     *
     * @mbg.generated
     */
    private String reportNumber;

    /**
     * Database Column Remarks:
     *   �?验项目名�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     * Database Column Remarks:
     *   �?验项目编�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.project_code
     *
     * @mbg.generated
     */
    private String projectCode;

    /**
     * Database Column Remarks:
     *   标本编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.specimen_code
     *
     * @mbg.generated
     */
    private String specimenCode;

    /**
     * Database Column Remarks:
     *   标本来源
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.specimen_source
     *
     * @mbg.generated
     */
    private String specimenSource;

    /**
     * Database Column Remarks:
     *   医院编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.hospital_code
     *
     * @mbg.generated
     */
    private String hospitalCode;

    /**
     * Database Column Remarks:
     *   报告时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.report_time
     *
     * @mbg.generated
     */
    private Date reportTime;

    /**
     * Database Column Remarks:
     *   抽取时间,数据同步�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.extract_time
     *
     * @mbg.generated
     */
    private Date extractTime;

    /**
     * Database Column Remarks:
     *   记录状�??:1-进行�?,2-完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.record_status
     *
     * @mbg.generated
     */
    private Integer recordStatus;

    /**
     * Database Column Remarks:
     *   预留字段1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.attribute1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   预留字段2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.attribute2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   预留字段3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.attribute3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   预留字段4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.attribute4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   预留字段5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column examine_info_report.attribute5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table examine_info_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.eir_id
     *
     * @return the value of examine_info_report.eir_id
     *
     * @mbg.generated
     */
    public Long getEirId() {
        return eirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.eir_id
     *
     * @param eirId the value for examine_info_report.eir_id
     *
     * @mbg.generated
     */
    public void setEirId(Long eirId) {
        this.eirId = eirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.patient_id
     *
     * @return the value of examine_info_report.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.patient_id
     *
     * @param patientId the value for examine_info_report.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.adminission_number
     *
     * @return the value of examine_info_report.adminission_number
     *
     * @mbg.generated
     */
    public String getAdminissionNumber() {
        return adminissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.adminission_number
     *
     * @param adminissionNumber the value for examine_info_report.adminission_number
     *
     * @mbg.generated
     */
    public void setAdminissionNumber(String adminissionNumber) {
        this.adminissionNumber = adminissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.application_number
     *
     * @return the value of examine_info_report.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.application_number
     *
     * @param applicationNumber the value for examine_info_report.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.report_number
     *
     * @return the value of examine_info_report.report_number
     *
     * @mbg.generated
     */
    public String getReportNumber() {
        return reportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.report_number
     *
     * @param reportNumber the value for examine_info_report.report_number
     *
     * @mbg.generated
     */
    public void setReportNumber(String reportNumber) {
        this.reportNumber = reportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.project_name
     *
     * @return the value of examine_info_report.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.project_name
     *
     * @param projectName the value for examine_info_report.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.project_code
     *
     * @return the value of examine_info_report.project_code
     *
     * @mbg.generated
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.project_code
     *
     * @param projectCode the value for examine_info_report.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.specimen_code
     *
     * @return the value of examine_info_report.specimen_code
     *
     * @mbg.generated
     */
    public String getSpecimenCode() {
        return specimenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.specimen_code
     *
     * @param specimenCode the value for examine_info_report.specimen_code
     *
     * @mbg.generated
     */
    public void setSpecimenCode(String specimenCode) {
        this.specimenCode = specimenCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.specimen_source
     *
     * @return the value of examine_info_report.specimen_source
     *
     * @mbg.generated
     */
    public String getSpecimenSource() {
        return specimenSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.specimen_source
     *
     * @param specimenSource the value for examine_info_report.specimen_source
     *
     * @mbg.generated
     */
    public void setSpecimenSource(String specimenSource) {
        this.specimenSource = specimenSource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.hospital_code
     *
     * @return the value of examine_info_report.hospital_code
     *
     * @mbg.generated
     */
    public String getHospitalCode() {
        return hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.hospital_code
     *
     * @param hospitalCode the value for examine_info_report.hospital_code
     *
     * @mbg.generated
     */
    public void setHospitalCode(String hospitalCode) {
        this.hospitalCode = hospitalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.report_time
     *
     * @return the value of examine_info_report.report_time
     *
     * @mbg.generated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.report_time
     *
     * @param reportTime the value for examine_info_report.report_time
     *
     * @mbg.generated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.extract_time
     *
     * @return the value of examine_info_report.extract_time
     *
     * @mbg.generated
     */
    public Date getExtractTime() {
        return extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.extract_time
     *
     * @param extractTime the value for examine_info_report.extract_time
     *
     * @mbg.generated
     */
    public void setExtractTime(Date extractTime) {
        this.extractTime = extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.record_status
     *
     * @return the value of examine_info_report.record_status
     *
     * @mbg.generated
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.record_status
     *
     * @param recordStatus the value for examine_info_report.record_status
     *
     * @mbg.generated
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.attribute1
     *
     * @return the value of examine_info_report.attribute1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.attribute1
     *
     * @param attribute1 the value for examine_info_report.attribute1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.attribute2
     *
     * @return the value of examine_info_report.attribute2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.attribute2
     *
     * @param attribute2 the value for examine_info_report.attribute2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.attribute3
     *
     * @return the value of examine_info_report.attribute3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.attribute3
     *
     * @param attribute3 the value for examine_info_report.attribute3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.attribute4
     *
     * @return the value of examine_info_report.attribute4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.attribute4
     *
     * @param attribute4 the value for examine_info_report.attribute4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column examine_info_report.attribute5
     *
     * @return the value of examine_info_report.attribute5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column examine_info_report.attribute5
     *
     * @param attribute5 the value for examine_info_report.attribute5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
}