package com.yx.cdss.extract.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table inspect_info_report
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InspectInfoReport implements Serializable {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.iir_id
     *
     * @mbg.generated
     */
    private Long iirId;

    /**
     * Database Column Remarks:
     *   患�?�ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     * Database Column Remarks:
     *   住院�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.adminission_number
     *
     * @mbg.generated
     */
    private String adminissionNumber;

    /**
     * Database Column Remarks:
     *   �?查申请单�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.application_number
     *
     * @mbg.generated
     */
    private String applicationNumber;

    /**
     * Database Column Remarks:
     *   �?查报告单�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.report_number
     *
     * @mbg.generated
     */
    private String reportNumber;

    /**
     * Database Column Remarks:
     *   �?查项目名�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.check_project_name
     *
     * @mbg.generated
     */
    private String checkProjectName;

    /**
     * Database Column Remarks:
     *   �?查项目编�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.check_project_code
     *
     * @mbg.generated
     */
    private String checkProjectCode;

    /**
     * Database Column Remarks:
     *   报告正文
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.report_body
     *
     * @mbg.generated
     */
    private String reportBody;

    /**
     * Database Column Remarks:
     *   报告结论
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.report_conclusion
     *
     * @mbg.generated
     */
    private String reportConclusion;

    /**
     * Database Column Remarks:
     *   �?查时�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.inspect_time
     *
     * @mbg.generated
     */
    private Date inspectTime;

    /**
     * Database Column Remarks:
     *   报告时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.report_time
     *
     * @mbg.generated
     */
    private Date reportTime;

    /**
     * Database Column Remarks:
     *   抽取时间,数据同步�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.extract_time
     *
     * @mbg.generated
     */
    private Date extractTime;

    /**
     * Database Column Remarks:
     *   记录状�??:1-进行�?,2-完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.record_status
     *
     * @mbg.generated
     */
    private Integer recordStatus;

    /**
     * Database Column Remarks:
     *   预留字段1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.attribute1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   预留字段2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.attribute2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   预留字段3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.attribute3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   预留字段4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.attribute4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   预留字段5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspect_info_report.attribute5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table inspect_info_report
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.iir_id
     *
     * @return the value of inspect_info_report.iir_id
     *
     * @mbg.generated
     */
    public Long getIirId() {
        return iirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.iir_id
     *
     * @param iirId the value for inspect_info_report.iir_id
     *
     * @mbg.generated
     */
    public void setIirId(Long iirId) {
        this.iirId = iirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.patient_id
     *
     * @return the value of inspect_info_report.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.patient_id
     *
     * @param patientId the value for inspect_info_report.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.adminission_number
     *
     * @return the value of inspect_info_report.adminission_number
     *
     * @mbg.generated
     */
    public String getAdminissionNumber() {
        return adminissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.adminission_number
     *
     * @param adminissionNumber the value for inspect_info_report.adminission_number
     *
     * @mbg.generated
     */
    public void setAdminissionNumber(String adminissionNumber) {
        this.adminissionNumber = adminissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.application_number
     *
     * @return the value of inspect_info_report.application_number
     *
     * @mbg.generated
     */
    public String getApplicationNumber() {
        return applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.application_number
     *
     * @param applicationNumber the value for inspect_info_report.application_number
     *
     * @mbg.generated
     */
    public void setApplicationNumber(String applicationNumber) {
        this.applicationNumber = applicationNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.report_number
     *
     * @return the value of inspect_info_report.report_number
     *
     * @mbg.generated
     */
    public String getReportNumber() {
        return reportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.report_number
     *
     * @param reportNumber the value for inspect_info_report.report_number
     *
     * @mbg.generated
     */
    public void setReportNumber(String reportNumber) {
        this.reportNumber = reportNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.check_project_name
     *
     * @return the value of inspect_info_report.check_project_name
     *
     * @mbg.generated
     */
    public String getCheckProjectName() {
        return checkProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.check_project_name
     *
     * @param checkProjectName the value for inspect_info_report.check_project_name
     *
     * @mbg.generated
     */
    public void setCheckProjectName(String checkProjectName) {
        this.checkProjectName = checkProjectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.check_project_code
     *
     * @return the value of inspect_info_report.check_project_code
     *
     * @mbg.generated
     */
    public String getCheckProjectCode() {
        return checkProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.check_project_code
     *
     * @param checkProjectCode the value for inspect_info_report.check_project_code
     *
     * @mbg.generated
     */
    public void setCheckProjectCode(String checkProjectCode) {
        this.checkProjectCode = checkProjectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.report_body
     *
     * @return the value of inspect_info_report.report_body
     *
     * @mbg.generated
     */
    public String getReportBody() {
        return reportBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.report_body
     *
     * @param reportBody the value for inspect_info_report.report_body
     *
     * @mbg.generated
     */
    public void setReportBody(String reportBody) {
        this.reportBody = reportBody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.report_conclusion
     *
     * @return the value of inspect_info_report.report_conclusion
     *
     * @mbg.generated
     */
    public String getReportConclusion() {
        return reportConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.report_conclusion
     *
     * @param reportConclusion the value for inspect_info_report.report_conclusion
     *
     * @mbg.generated
     */
    public void setReportConclusion(String reportConclusion) {
        this.reportConclusion = reportConclusion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.inspect_time
     *
     * @return the value of inspect_info_report.inspect_time
     *
     * @mbg.generated
     */
    public Date getInspectTime() {
        return inspectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.inspect_time
     *
     * @param inspectTime the value for inspect_info_report.inspect_time
     *
     * @mbg.generated
     */
    public void setInspectTime(Date inspectTime) {
        this.inspectTime = inspectTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.report_time
     *
     * @return the value of inspect_info_report.report_time
     *
     * @mbg.generated
     */
    public Date getReportTime() {
        return reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.report_time
     *
     * @param reportTime the value for inspect_info_report.report_time
     *
     * @mbg.generated
     */
    public void setReportTime(Date reportTime) {
        this.reportTime = reportTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.extract_time
     *
     * @return the value of inspect_info_report.extract_time
     *
     * @mbg.generated
     */
    public Date getExtractTime() {
        return extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.extract_time
     *
     * @param extractTime the value for inspect_info_report.extract_time
     *
     * @mbg.generated
     */
    public void setExtractTime(Date extractTime) {
        this.extractTime = extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.record_status
     *
     * @return the value of inspect_info_report.record_status
     *
     * @mbg.generated
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.record_status
     *
     * @param recordStatus the value for inspect_info_report.record_status
     *
     * @mbg.generated
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.attribute1
     *
     * @return the value of inspect_info_report.attribute1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.attribute1
     *
     * @param attribute1 the value for inspect_info_report.attribute1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.attribute2
     *
     * @return the value of inspect_info_report.attribute2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.attribute2
     *
     * @param attribute2 the value for inspect_info_report.attribute2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.attribute3
     *
     * @return the value of inspect_info_report.attribute3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.attribute3
     *
     * @param attribute3 the value for inspect_info_report.attribute3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.attribute4
     *
     * @return the value of inspect_info_report.attribute4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.attribute4
     *
     * @param attribute4 the value for inspect_info_report.attribute4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspect_info_report.attribute5
     *
     * @return the value of inspect_info_report.attribute5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspect_info_report.attribute5
     *
     * @param attribute5 the value for inspect_info_report.attribute5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
}