package com.yx.cdss.extract.model.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table medical_orders
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class MedicalOrders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.mo_id
     *
     * @mbg.generated
     */
    private Long moId;

    /**
     * Database Column Remarks:
     *   医嘱ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.medical_orders_id
     *
     * @mbg.generated
     */
    private String medicalOrdersId;

    /**
     * Database Column Remarks:
     *   患�?�ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.patient_id
     *
     * @mbg.generated
     */
    private String patientId;

    /**
     * Database Column Remarks:
     *   住院�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.admission_number
     *
     * @mbg.generated
     */
    private String admissionNumber;

    /**
     * Database Column Remarks:
     *   医嘱类型(1-长嘱,2-临嘱)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.orders_type
     *
     * @mbg.generated
     */
    private String ordersType;

    /**
     * Database Column Remarks:
     *   医医嘱类�?:1-药品;2-�?�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.orders_category
     *
     * @mbg.generated
     */
    private String ordersCategory;

    /**
     * Database Column Remarks:
     *   医嘱状�??:1-执行�?,2-已执�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.orders_status
     *
     * @mbg.generated
     */
    private String ordersStatus;

    /**
     * Database Column Remarks:
     *   下医嘱时�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.begin_orders_time
     *
     * @mbg.generated
     */
    private Date beginOrdersTime;

    /**
     * Database Column Remarks:
     *   医生编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.doctor_no
     *
     * @mbg.generated
     */
    private String doctorNo;

    /**
     * Database Column Remarks:
     *   医生姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.doctor_name
     *
     * @mbg.generated
     */
    private String doctorName;

    /**
     * Database Column Remarks:
     *   �?属医院编�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.hosptal_code
     *
     * @mbg.generated
     */
    private String hosptalCode;

    /**
     * Database Column Remarks:
     *   抽取时间,数据同步�?
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.extract_time
     *
     * @mbg.generated
     */
    private Date extractTime;

    /**
     * Database Column Remarks:
     *   记录状�??:1-进行�?,2-完成
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.record_status
     *
     * @mbg.generated
     */
    private Integer recordStatus;

    /**
     * Database Column Remarks:
     *   预留字段1
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.attribute1
     *
     * @mbg.generated
     */
    private String attribute1;

    /**
     * Database Column Remarks:
     *   预留字段2
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.attribute2
     *
     * @mbg.generated
     */
    private String attribute2;

    /**
     * Database Column Remarks:
     *   预留字段3
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.attribute3
     *
     * @mbg.generated
     */
    private String attribute3;

    /**
     * Database Column Remarks:
     *   预留字段4
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.attribute4
     *
     * @mbg.generated
     */
    private String attribute4;

    /**
     * Database Column Remarks:
     *   预留字段5
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column medical_orders.attribute5
     *
     * @mbg.generated
     */
    private String attribute5;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table medical_orders
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.mo_id
     *
     * @return the value of medical_orders.mo_id
     *
     * @mbg.generated
     */
    public Long getMoId() {
        return moId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.mo_id
     *
     * @param moId the value for medical_orders.mo_id
     *
     * @mbg.generated
     */
    public void setMoId(Long moId) {
        this.moId = moId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.medical_orders_id
     *
     * @return the value of medical_orders.medical_orders_id
     *
     * @mbg.generated
     */
    public String getMedicalOrdersId() {
        return medicalOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.medical_orders_id
     *
     * @param medicalOrdersId the value for medical_orders.medical_orders_id
     *
     * @mbg.generated
     */
    public void setMedicalOrdersId(String medicalOrdersId) {
        this.medicalOrdersId = medicalOrdersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.patient_id
     *
     * @return the value of medical_orders.patient_id
     *
     * @mbg.generated
     */
    public String getPatientId() {
        return patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.patient_id
     *
     * @param patientId the value for medical_orders.patient_id
     *
     * @mbg.generated
     */
    public void setPatientId(String patientId) {
        this.patientId = patientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.admission_number
     *
     * @return the value of medical_orders.admission_number
     *
     * @mbg.generated
     */
    public String getAdmissionNumber() {
        return admissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.admission_number
     *
     * @param admissionNumber the value for medical_orders.admission_number
     *
     * @mbg.generated
     */
    public void setAdmissionNumber(String admissionNumber) {
        this.admissionNumber = admissionNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.orders_type
     *
     * @return the value of medical_orders.orders_type
     *
     * @mbg.generated
     */
    public String getOrdersType() {
        return ordersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.orders_type
     *
     * @param ordersType the value for medical_orders.orders_type
     *
     * @mbg.generated
     */
    public void setOrdersType(String ordersType) {
        this.ordersType = ordersType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.orders_category
     *
     * @return the value of medical_orders.orders_category
     *
     * @mbg.generated
     */
    public String getOrdersCategory() {
        return ordersCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.orders_category
     *
     * @param ordersCategory the value for medical_orders.orders_category
     *
     * @mbg.generated
     */
    public void setOrdersCategory(String ordersCategory) {
        this.ordersCategory = ordersCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.orders_status
     *
     * @return the value of medical_orders.orders_status
     *
     * @mbg.generated
     */
    public String getOrdersStatus() {
        return ordersStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.orders_status
     *
     * @param ordersStatus the value for medical_orders.orders_status
     *
     * @mbg.generated
     */
    public void setOrdersStatus(String ordersStatus) {
        this.ordersStatus = ordersStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.begin_orders_time
     *
     * @return the value of medical_orders.begin_orders_time
     *
     * @mbg.generated
     */
    public Date getBeginOrdersTime() {
        return beginOrdersTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.begin_orders_time
     *
     * @param beginOrdersTime the value for medical_orders.begin_orders_time
     *
     * @mbg.generated
     */
    public void setBeginOrdersTime(Date beginOrdersTime) {
        this.beginOrdersTime = beginOrdersTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.doctor_no
     *
     * @return the value of medical_orders.doctor_no
     *
     * @mbg.generated
     */
    public String getDoctorNo() {
        return doctorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.doctor_no
     *
     * @param doctorNo the value for medical_orders.doctor_no
     *
     * @mbg.generated
     */
    public void setDoctorNo(String doctorNo) {
        this.doctorNo = doctorNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.doctor_name
     *
     * @return the value of medical_orders.doctor_name
     *
     * @mbg.generated
     */
    public String getDoctorName() {
        return doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.doctor_name
     *
     * @param doctorName the value for medical_orders.doctor_name
     *
     * @mbg.generated
     */
    public void setDoctorName(String doctorName) {
        this.doctorName = doctorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.hosptal_code
     *
     * @return the value of medical_orders.hosptal_code
     *
     * @mbg.generated
     */
    public String getHosptalCode() {
        return hosptalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.hosptal_code
     *
     * @param hosptalCode the value for medical_orders.hosptal_code
     *
     * @mbg.generated
     */
    public void setHosptalCode(String hosptalCode) {
        this.hosptalCode = hosptalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.extract_time
     *
     * @return the value of medical_orders.extract_time
     *
     * @mbg.generated
     */
    public Date getExtractTime() {
        return extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.extract_time
     *
     * @param extractTime the value for medical_orders.extract_time
     *
     * @mbg.generated
     */
    public void setExtractTime(Date extractTime) {
        this.extractTime = extractTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.record_status
     *
     * @return the value of medical_orders.record_status
     *
     * @mbg.generated
     */
    public Integer getRecordStatus() {
        return recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.record_status
     *
     * @param recordStatus the value for medical_orders.record_status
     *
     * @mbg.generated
     */
    public void setRecordStatus(Integer recordStatus) {
        this.recordStatus = recordStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.attribute1
     *
     * @return the value of medical_orders.attribute1
     *
     * @mbg.generated
     */
    public String getAttribute1() {
        return attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.attribute1
     *
     * @param attribute1 the value for medical_orders.attribute1
     *
     * @mbg.generated
     */
    public void setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.attribute2
     *
     * @return the value of medical_orders.attribute2
     *
     * @mbg.generated
     */
    public String getAttribute2() {
        return attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.attribute2
     *
     * @param attribute2 the value for medical_orders.attribute2
     *
     * @mbg.generated
     */
    public void setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.attribute3
     *
     * @return the value of medical_orders.attribute3
     *
     * @mbg.generated
     */
    public String getAttribute3() {
        return attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.attribute3
     *
     * @param attribute3 the value for medical_orders.attribute3
     *
     * @mbg.generated
     */
    public void setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.attribute4
     *
     * @return the value of medical_orders.attribute4
     *
     * @mbg.generated
     */
    public String getAttribute4() {
        return attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.attribute4
     *
     * @param attribute4 the value for medical_orders.attribute4
     *
     * @mbg.generated
     */
    public void setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column medical_orders.attribute5
     *
     * @return the value of medical_orders.attribute5
     *
     * @mbg.generated
     */
    public String getAttribute5() {
        return attribute5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column medical_orders.attribute5
     *
     * @param attribute5 the value for medical_orders.attribute5
     *
     * @mbg.generated
     */
    public void setAttribute5(String attribute5) {
        this.attribute5 = attribute5;
    }
}